language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - pablo.perezfer@alumnos.upm.es
script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify